name: clang-format Check
on:
  push: 
    branches:
      - dev
  pull_request: yes

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: self-hosted
    needs: checkout
    steps:
    - uses: actions/checkout@v3
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: http://github.com/jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '15'
        check-path: 'ccsrc'