#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "usage: format-cc [DIR] [FLAGS]"
    exit
fi

if [ $CLANG_PATH ]; then
    PATH=$PATH:$CLANG_PATH
fi

FLAGS="-i"
if [ $2 ]; then
    FLAGS=$2
fi

find $1 -name *.cc -o -name *.hpp -o -name *.cpp -name *.h -o -name *.hh | xargs clang-format $FLAGS